### ISSUE TITLE
AU Linux kernel autumn 2017 запрос на проверку mutex Тонких Андрей

### ISSUE THREAD

**Issue by xosmig** [xosmig/au-linux-kernel-autumn-2017#5]
2886493ed8188355c608827a528bebf4b48e41c3

**Comment by xosmig** [comment]
6eff7c0a25a0091cbb4887142cfd334e86fef4d8
optimized the solution by adding `shared_spin_trylock_once` function

**Comment by eabatalov** [comment]
Very very good. 95% for the task. Thank you!

**Comment by xosmig** [comment]
Thank you for reviewing the code!
